name: Push directory to another repository
on: 
  pull_request:
    branches:
      - "**"
jobs:
  deploy-user-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pushes user docs to organization repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          # F0urchette personal access token
          API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          source-directory: 'user-docs'
          target-branch: gh-pages
          destination-github-username: 'TestingGithubPages'
          destination-repository-name: 'TestingGithubPages.github.io'
          user-email: user@doc.fr
